#
#  Makefile for Examples, Appendix D
#

all:  change-wrong change-right traverse mystrlen copies addresses typedef-demo

change-wrong: change-wrong.c
	gcc -o change-wrong change-wrong.c

change-right: change-right.c
	gcc -o change-right change-right.c

traverse: traverse.c
	gcc -o traverse traverse.c

copies: copies.c
	gcc -o copies copies.c
	
mystrlen: mystrlen.c
	gcc -o mystrlen mystrlen.c
	
addresses: addresses.c
	gcc -o addresses addresses.c

typedef-demo: typedef-demo.c
	gcc -o typedef-demo typedef-demo.c


clean: 
	rm change-wrong change-right traverse mystrlen copies addresses typedef-demo 
