all: output input padding input-setw eof-demo input-validate line-count random-access binary-io

output: output.cpp
	g++ -o output output.cpp

input: input.cpp
	g++ -o input input.cpp

padding: padding.cpp
	g++ -o padding padding.cpp

input-setw: input-setw.cpp
	g++ -o input-setw input-setw.cpp

eof-demo: eof-demo.cpp
	g++ -o eof-demo eof-demo.cpp

input-validate: input-validate.cpp
	g++ -o input-validate input-validate.cpp

line-count: line-count.cpp
	g++ -o line-count line-count.cpp

random-access: random-access.cpp
	g++ -o random-access random-access.cpp

binary-io: binary-io.cpp
	g++ -o binary-io binary-io.cpp

clean: 
	rm output input padding input-setw eof-demo input-validate line-count random-access binary-io

