all: vector-demo list-demo set-demo map-demo find-demo merge-demo accumulate-demo accumulate-product function-object pqueue-demo 

vector-demo: vector-demo.cpp
	g++ -o vector-demo vector-demo.cpp

list-demo: list-demo.cpp
	g++ -o list-demo list-demo.cpp

set-demo: set-demo.cpp
	g++ -o set-demo set-demo.cpp

map-demo: map-demo.cpp
	g++ -o map-demo map-demo.cpp

find-demo: find-demo.cpp
	g++ -o find-demo find-demo.cpp

merge-demo: merge-demo.cpp
	g++ -o merge-demo merge-demo.cpp

accumulate-demo: accumulate-demo.cpp
	g++ -o accumulate-demo accumulate-demo.cpp

accumulate-product: accumulate-product.cpp
	g++ -o accumulate-product accumulate-product.cpp

function-object: function-object.cpp
	g++ -o function-object function-object.cpp

pqueue-demo: pqueue-demo.cpp
	g++ -o pqueue-demo pqueue-demo.cpp


clean: 
	rm vector-demo list-demo set-demo map-demo find-demo merge-demo accumulate-demo accumulate-product function-object pqueue-demo

