all: output input const-param ref-return multiply-wrong multiply def-param scope-op bool-demo string-demo string-demo2

output:  output.cpp
	g++ -o output output.cpp

input:  input.cpp
	g++ -o input input.cpp

const-param: const-param.cpp
	g++ -o const-param const-param.cpp

ref-return: ref-return.cpp
	g++ -o ref-return ref-return.cpp

multiply-wrong: multiply-wrong.cpp
	g++ -o multiply-wrong multiply-wrong.cpp

multiply: multiply.cpp
	g++ -o multiply multiply.cpp

def-param: def-param.cpp
	g++ -o def-param def-param.cpp

scope-op: scope-op.cpp
	g++ -o scope-op scope-op.cpp

bool-demo: bool-demo.cpp
	g++ -o bool-demo bool-demo.cpp

string-demo: string-demo.cpp
	g++ -o string-demo string-demo.cpp

string-demo2: string-demo2.cpp
	g++ -o string-demo2 string-demo2.cpp

clean: 
	rm output input const-param ref-return multiply-wrong multiply def-param scope-op bool-demo string-demo string-demo2
