#
#  Makefile for Examples, Appendix B
#

all: arrays headers1 headers2 square 

arrays: arrays.c
	gcc -o arrays arrays.c

headers1: headers1.c
	gcc -o headers1 headers1.c

headers2: headers2.c
	gcc -o headers2 headers2.c -lm

square: square.c
	gcc -o square square.c

clean: 
	rm arrays headers1 headers2 square 
