#
#  Makefile for Examples, Appendix A
#

all: another-sample arrays functions printf-demo prototypes sample scanf-demo 

another-sample: another-sample.c
	gcc -o another-sample another-sample.c
	
arrays: arrays.c
	gcc -o arrays arrays.c	
	
functions: functions.c
	gcc -o functions functions.c	

printf-demo: printf-demo.c
	gcc -o printf-demo printf-demo.c

prototypes: prototypes.c
	gcc -o prototypes prototypes.c	
	
sample: sample.c
	gcc -o sample sample.c

scanf-demo: scanf-demo.c
	gcc -o scanf-demo scanf-demo.c

clean: 
	rm another-sample arrays functions printf-demo prototypes sample scanf-demo
	
