#
#  Makefile for Solutions, Appendix A
#

all: A-1 A-2 A-3 A-4

A-1: A-1.c
	gcc -o A-1 A-1.c

A-2: A-2.c
	gcc -o A-2 A-2.c

A-3: A-3.c
	gcc -o A-3 A-3.c

A-4: A-4.c
	gcc -o A-4 A-4.c

clean: 
	rm A-1 A-2 A-3 A-4
